### ISSUE TITLE
API Url - HTTP vs. HTTPS vs. Unsigned Certificates

### ISSUE THREAD

**Issue by cewald** [lizards-and-pumpkins/magento-connector#361]
If you use a self signed certificate, e.g. while development, the api request during an export will always fail because of a empty response body in http request.

I could fix it by either using a HTTP url instead HTTPS or by adding `"verify_peer" => false, "verify_peer_name" => false` to the request context in the `doPutRequests` and `doGetRequest` methods of `lib/LizardsAndPumpkins/src/Api/PhpStreamHttpApiClient.php`.

This might not be a typical setting for production but could be a bit confusing while development.

**Comment by Schrank** [comment]
We should implement a debug/developer mode which turns off checking.

**Comment by Vinai** [comment]
I suggest adding a `PhpStreamHttpApiClient::insecure()` named constructor which will instantiate the client and set flags that disable the certificate verification.

Then in `\LizardsAndPumpkins_MagentoConnector_Helper_Factory::createLizardsAndPumpkinsApi()` either `new` or the new constructor can be used depending on a Magento system config setting.  

Instead of calling it `debug` mode, lets call it `Disable HTTPS certificate verification for API requests`.
